name: cnn1d
# last num_channels * grid size should match transformer input
channels: [1, 8, 8, 1]
# values per layer
kernel_size : [5, 5, 3]
padding : [ 2, 1, 0]

# pooling
pool_kernel: 2
pool_stride: 2

# replace value in code
grid_dim: True

#positional_encoding
pe : original_add