# @package _group_
# see torch.pre_processing.lr_scheduler.ReduceLROnPlateau for details
name: ReduceLROnPlateau
monitor: val_loss

mode: min
factor: 0.75
patience: 20
min_lr: 1e-12
eps: 1e-8
verbose: False
